# Jumper config file

# Min and max distance (in meters) that the player can teleport to.
# Setting max to 0 will automatically set max to the server's view distance.
distance:
  min: 0
  max: 0

# Amount by which to increase the player's exhaustion for every
# meter traveled by teleporting.  For perspective, a player's
# exhaustion is increased by 0.1 per meter while sprinting.
# http://minecraft.gamepedia.com/Hunger#Exhaustion_level_increase
exhaustion_per_meter: 0.0

# If player's food bar is less than this, they will be unable to teleport.
# Range: 0% (starving) to 100% (full).
min_food: 0

# If player's health is less than this, they will be unable to teleport.
# Range: 0% (dead) to 100% (full health).
min_health: 0

# Whether or not to play a teleport sound
sound: true