name: Jumper
version: "1.3.1"
author: Austin Bowen <austin.bowen.314@gmail.com>
main: me.saltyhash.jumper.Jumper
api-version: "1.13"
commands:
  jumper:
    description: Display instructions on how to use Jumper
    usage: /<command>
  jumper reload:
    description: Reload config file
    usage: /<command>
  jumper version:
    description: Display the plugin version and authors
    usage: /<command>
permissions:
  jumper.reload:
    description: Allow using the reload subcommand
    default: op
  jumper.use:
    description: Allow the player to teleport
    default: true
  jumper.version:
    description: Allow using the version subcommand
    default: op