name: Jumper
version: 1.3
author: Austin Bowen <austin.bowen.314@gmail.com>
main: me.saltyhash.jumper.Jumper
commands:
permissions:
  jumper.use:
    description: Allows the player to use Jumper.
    default: true